name: cypress e2e
on:
  push:
    branches:    
      - 'master'
    paths:
      - 'packages/login/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/login
          build: yarn run build
          start: yarn run start
          wait-on: 'http://localhost:3001'