name: cypress e2e
on:
  push:
    branches:    
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy: 
      # won't stop all app tests if one fails
      fail-fast: false
      matrix:
        cypress:
          - working_directory: packages/login/
          - working_directory: packages/web-app/

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{ matrix.cypress.working_directory }}
          build: yarn run build
          start: yarn run start
          wait-on: 'http://localhost:5000'